### ISSUE TITLE
Detect if emacs version supports dynamic modules

### ISSUE THREAD

**Issue by martin5233** [weirdNox/emacs-gdb#1]
When trying this out, I just stumbled across a minor problem, that my emacs version did not support dynamic modules. The default, when building emacs on Linux, is that dynamic modules are disabled, so I had to recompile emacs first. This could be checked, when using the module-file-suffix in the code of your library. This would other people probably save time, when trying to investigate, why it doesn't work on the first attempt.

**Comment by weirdNox** [comment]
Should it just show a message that says it is not available? Did the package install in you setup without dynamic modules? Or did it error out because of that module suffix variable?

**Comment by ether42** [comment]
An error message is probably good enough.
At least, it will be better than the current one :)
```
$ make gdb-module
cc     gdb-module.c   -o gdb-module
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'gdb-module' failed
make: *** [gdb-module] Error 1
```
As OP said, `module-file-suffix` being nil the make command is invalid.

**Comment by weirdNox** [comment]
Ok, thanks, I'll see if it works better with an error :)
