### ISSUE TITLE
packaging request: melpa

### ISSUE THREAD

**Issue by silvioprog** [weirdNox/emacs-gdb#11]
Hi.

It would be nice to publish this package at https://melpa.org, one of the most popular package archive for Emacs.

Cheers

**Comment by weirdNox** [comment]
Hi there!

I agree that it is useful to have this package published in MELPA, but I've submitted a package there before and got the idea that they don't like "clones" and similarly-named packages in there (and there is a builtin Emacs package with a _very_ similar name).

Also, in my other published package, I can't really deal with all the feature requests and reports, so I am trying to avoid looking like I am willing to support this by packaging it for MELPA. I am not even sure if I am going to use Emacs for much longer.

Finally, while you can simply download the source and place it with your dotfiles, Quelpa and straight.el (which is what I am using now) work seamlessly with this kind of packages.

Anyway, if anyone wants to step up and maintain this package, feel free to fork this and publish it on MELPA! :D
Thanks for the suggestion, and sorry for the inconvenience!
