### ISSUE TITLE
.gdbinit is ignored

### ISSUE THREAD

**Issue by martin5233** [weirdNox/emacs-gdb#3]
It seems, that emacs-gdb starts gdb with the option -nx, which prevents the usage of .gdbinit. This should probably be configurable, as in my setup I need .gdbinit, so I currently have to explicitly source it.

Thanks a lot for this great new package! It seems extremely promising and I am happy to help to improve it where possible. There are still a few minor quirks in it, but it's great!

**Comment by weirdNox** [comment]
Thanks for the kind words and the report! Yes, making it configurable is trivial.
I added that flag in the first place because I had GDB Dashboard installed, and it outputted escape codes for its interface.

**Comment by weirdNox** [comment]
You now have the variable `gdb-ignore-gdbinit`, set it to `nil` :)
