### ISSUE TITLE
Error on gdb-executable

### ISSUE THREAD

**Issue by mrndrsn** [weirdNox/emacs-gdb#7]
I tried to use emacs-gdb for the first time. The installation processed without any problems after adding the use-package-quelpa instructions of the README to my init.el. But when i try to run gdb-executable, emacs prints out the message:

error in process filter: ansi-color-process-output: Wrong type argument: processp, nil
error in process filter: Wrong type argument: processp, nil

Does someone got the same issue and solved it maybe?

**Comment by weirdNox** [comment]
Could you trigger the error after `toggle-debug-on-error` and paste the backtrace? I can't reproduce it, so you must have a configuration related to that somewhere in your config or installed packages. Do you have any reference to `ansi-color-process-output` in your config?

**Comment by fabrice-baray** [comment]
Hi,

Maybe not the same as mrndrsn, but it looks like I have a similar issue. The backtrace is the following in my case:

Debugger entered--Lisp error: (wrong-type-argument processp nil)
  process-mark(nil)
  ansi-color-process-output("License GPLv3+: GNU GPL version 3 or later <http:/...")
  run-hook-with-args(ansi-color-process-output "License GPLv3+: GNU GPL version 3 or later <http:/...")
  comint-output-filter(#<process GDB> "~\"License GPLv3+: GNU GPL version 3 or later <http...")


if I expand one of the string until the end I get this:
"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\nThis GDB was configured as \"x86_64-pc-linux-gnu\".\nType \"show configuration\" for configuration details.\nFor bug reporting instructions, please see:\n<http://www.gnu.org/software/gdb/bugs/>.\nFind the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.\nFor help, type \"help\".\nType \"apropos word\" to search for commands related to \"word\".\n(gdb) "

I don't have anything about ansi-color-process-output in my config.

  Fabrice

**Comment by weirdNox** [comment]
Ok, after some digging I found that `ansi-color-process-output` is on `comint-output-filter-functions` by default, so it is being called by that.

Could you execute `(current-buffer)` and `(get-buffer-process (current-buffer))` when the error occurs (using the command bound to `e` by default, `debugger-eval-expression`)?

Are you using the latest version of Emacs (26.2) and GDB (8.3)?

**Comment by fabrice-baray** [comment]
current-buffer returns: #<buffer *GDB: Comint - binary_name*>
get-buffer-process...  returns: nil

emacs version is 27.0.50

buffers opened at the time it fails:
*GDB: Comint - binary_name*
*GDB: Inferior I/O - binary_name*

**Comment by weirdNox** [comment]
Ok, I'll try the master branch to see if that's the problem

**Comment by fabrice-baray** [comment]
I was on gdb 7.12, just tied with gdb 8.3 and it is the same.

**Comment by weirdNox** [comment]
I just verified, it is indeed due to the Emacs version, it also crashes for me on the master branch. I'll have to see if this is caused by a problem or if it is caused by a permanent change. Thanks for the report!

**Comment by fabrice-baray** [comment]
Ok Thanks! Meanwhile I can actually get emacs 26.2 and try with this. Best Regards.

**Comment by weirdNox** [comment]
I think I found the problem! It was wrong on my side since the beginning but, somehow, it worked on previous versions... :D

You may do a `quelpa-upgrade` and test it out, I didn't test much besides opening and seeing if it could break at main, but it looks like it is fixed :)

**Comment by fabrice-baray** [comment]
Much better, I don't have the  error anymore. Thanks!

**Comment by weirdNox** [comment]
Thanks for the confirmation :)
