### ISSUE TITLE
How to use a specific gdb?

### ISSUE THREAD

**Issue by lucaspeixotot** [weirdNox/emacs-gdb#9]
I'm working with embedded systems and for them I use a specific arm gdb, how can I change the gdb executable that is used in this package? I really liked what you did with this package, is awesome.

**Comment by weirdNox** [comment]
Thanks! 
I have added support for changing GDB's executable name with the variable `gdb-executable-name`.
You may now do something like this in your config:
```elisp
(defun gdb-arm (&rest args)
  "ARM version of `gdb-executable'"
  (interactive (advice-eval-interactive-spec (cadr (interactive-form #'gdb-executable))))
  (let ((funcall (if (called-interactively-p 'any)
                     #'funcall-interactively
                   #'funcall))
        (exec-path (append "/new/path" exec-path))
        (gdb-executable-name "gdb-with-different-name"))
   (apply funcall #'gdb-executable args)))
```

If you only need a different path, change `exec-path`. You may also use something like `"/usr/bin/gdb-arm"` in `gdb-executable-name` directly.

**Comment by erusyd** [comment]
Run gdb-arm, it complains **does not support non-stop mode**:
![image](https://user-images.githubusercontent.com/1529102/227501200-c29d3451-fa54-4d20-9c1a-ae1d11d5e251.png)
The gdb server is at port 4242:
![image](https://user-images.githubusercontent.com/1529102/227501239-388d4c94-9fff-4712-902b-9c21195aeeef.png)

If I use gud-gdb with `arm-none-eabi-gdb --fullname firmware.elf`, it succeeds:
![image](https://user-images.githubusercontent.com/1529102/227501970-12607133-f2c2-4490-9ecb-9dd59af329a4.png)
